services:
  app:
    build: .
    container_name: slim_app
    restart: always
    depends_on:
      db:
        condition: service_healthy  # Espera a que la DB esté lista
    environment:
      DB_HOST: db
      DB_NAME: lead_db
      DB_USER: root
      DB_PASS: root
      EXTERNAL_API_URL: https://mock-api.com/marketing-webhooks
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lead_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

volumes:
  db_data:
